### ISSUE TITLE
[Bug]: How add a configured ss over websocket instance as access key?

### ISSUE THREAD

**Issue by qluo1** [Jigsaw-Code/outline-apps#2423]
### Application

Outline Client

### Describe the bug

have a self-configured  websocket /  shadowsocks instance. 

now the issue is how to add an access key for this instance? what is the format of new access key? 

the outline client don't like the yaml format?

web:
  servers:
    - id: my_web_server
      listen:
        - "127.0.0.1:8000"

services:
  - listeners:
      - type: websocket-stream
        web_server: my_web_server
        path: "/SECRET/tcp"  # Prevent probing by serving under a secret path.
      - type: websocket-packet
        web_server: my_web_server
        path: "/SECRET/udp"  # Prevent probing by serving under a secret path.
    keys:
      - id: user-0
        cipher: chacha20-ietf-poly1305
        secret: Secret0

### Steps to reproduce

copy yaml with hostname, complain invalid access key.

### Outline Version

1.15.0

### What operation system are you using?

iOS

**Comment by qluo1** [comment]
update: the pasted client side config as following.


transport:
  $type: tcpudp

  tcp:
    $type: shadowsocks

    endpoint:
      $type: websocket
      url: wss://xxxx/SECRET/tcp
    cipher: chacha20-ietf-poly1305
    secret: secret

  udp:
    $type: shadowsocks

    endpoint:
      $type: websocket
      url: wss://xxxx/SECRET/udp
    cipher: chacha20-ietf-poly1305
    secret: secret

**Comment by sbruens** [comment]
What error are you seeing? Your client side config has some formatting issues. Fixing that, it would look like this:

```
transport:
  $type: tcpudp

  tcp:
    $type: shadowsocks

    endpoint:
      $type: websocket
      url: wss://xxxx/SECRET/tcp
    cipher: chacha20-ietf-poly1305
    secret: secret

  udp:
    $type: shadowsocks

    endpoint:
      $type: websocket
      url: wss://xxxx/SECRET/udp
    cipher: chacha20-ietf-poly1305
    secret: secret
```

That seems right to me at first glance, assuming the secret matches. What does the client error show?
